@startuml
'https://plantuml.com/object-diagram

object "<u>Document: myDocument</u>" as myDocument{
    characters = [H, e, l, l, o, W, o, r, l, d, C, S, 4, 8, 0, 0]
    propertiesFactory
}

object "<u>CharacterPropertiesFactory: factory</u>" as factory{
    flyweights = {"Arial", "Black", 11}
}

object "<u>CharacterProperties: defaultProperty</u>" as defaultProperty{
    font = "Arial"
    color = "Black"
    size = 11
}

object "<u>Character: char_H</u>" as char1{
    character: "H"
    characterProperty: defaultProperty
}

object "<u>Character: char_e</u>" as char2{
    character: "e"
    characterProperty: defaultProperty
}

object "<u>Character: char_l1</u>" as char3{
    character: "l"
    characterProperty: defaultProperty
}

object "<u>Character: char_l2</u>" as char4{
    character: "l"
    characterProperty: defaultProperty
}

object "<u>Character: char_o1</u>" as char5{
    character: "o"
    characterProperty: defaultProperty
}

object "<u>Character: char_W</u>" as char6{
    character: "W"
    characterProperty: defaultProperty
}

object "<u>Character: char_o2</u>" as char7{
    character: "o"
    characterProperty: defaultProperty
}

object "<u>Character: char_r</u>" as char8{
    character: "r"
    characterProperty: defaultProperty
}

object "<u>Character: char_l3</u>" as char9{
    character: "l"
    characterProperty: defaultProperty
}

object "<u>Character: char_d</u>" as char10{
    character: "d"
    characterProperty: defaultProperty
}

object "<u>Character: char_C</u>" as char11{
    character: "C"
    characterProperty: defaultProperty
}

object "<u>Character: char_S</u>" as char12{
    character: "S"
    characterProperty: defaultProperty
}

object "<u>Character: char:4</u>" as char13{
    character: "4"
    characterProperty: defaultProperty
}

object "<u>Character: char_8</u>" as char14{
    character: "8"
    characterProperty: defaultProperty
}

object "<u>Character: char_0_1</u>" as char15{
    character: "0"
    characterProperty: defaultProperty
}

object "<u>Character: char_0_2</u>" as char16{
    character: "0"
    characterProperty: defaultProperty
}

myDocument --> factory
myDocument o-U- char1
myDocument o-U- char2
myDocument o-U- char3
myDocument o-U- char4
myDocument o-U- char5
myDocument o-U- char6
myDocument o-U- char7
myDocument o-U- char8
myDocument o-D- char9
myDocument o-D- char10
myDocument o-D- char11
myDocument o-D- char12
myDocument o-D- char13
myDocument o-D- char14
myDocument o-D- char15
myDocument o-D- char16

factory --> defaultProperty
char1 --> defaultProperty
char2 --> defaultProperty
char3 --> defaultProperty
char4 --> defaultProperty
char5 --> defaultProperty
char6 --> defaultProperty
char7 --> defaultProperty
char8 --> defaultProperty
char9 --> defaultProperty
char10 --> defaultProperty
char11 --> defaultProperty
char12 --> defaultProperty
char13 --> defaultProperty
char14 --> defaultProperty
char15 --> defaultProperty
char16 --> defaultProperty

@enduml
